mysql_credentials:
  host: localhost
  port: 3306
  username: root
  password: pa55w0rd
  database: huskrtp
  params: '?autoReconnect=true&useSSL=false'
  player_table_name: huskrtp_players
  connection_pool_options:
    maximum_pool_size: 10
    minimum_idle: 10
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000
redis_credentials:
  host: localhost
  port: 6379
  password:
load_balancing:
  method: random
  plan:
    average_player_count_days: 7
    update_frequency_mins: 1
max_rtp_attempts: 10
rtp_time_out_seconds: 20
this_server_id: server1
last_rtp_on_cooldown: true
default_rtp_group: group1
debug_logging: false
groups:
  group1:
    table_name: huskrtp_group_1
    cooldown_minutes: 6
    servers_worlds:
      server1:
        - world
        - worldcustomgen
      server2:
        - world
        - worldgen2
  group2:
    table_name: huskrtp_group_2
    cooldown_minutes: 3
    servers_worlds:
      server3:
        - worldcustomgen