name: HuskBungeeRTP
version: ${project.version}
main: me.william278.huskbungeertp.HuskBungeeRTP
api-version: 1.16
author: William278
website: ${project.url}
description: ${project.description}
libraries:
  - 'redis.clients:jedis:${jedis.version}'
depend:
  - HuskHomes
  - Vault

commands:
  rtp:
    usage: /rtp [player] [group] [biome]
    description: Randomly teleport a player
    permission: huskrtp.command.rtp
    aliases: [brtp, hbrtp, randomtp]
  huskbungeertp:
    usage: /huskbungeertp <about/groups/playercounts/reload>
    description: View and manage plugin details
    permission: huskrtp.command.admin
permissions:
  huskrtp.*:
    description: Lets you use all HuskBungeeRTP commands
    default: op
    children:
      - huskrtp.command.rtp
  huskrtp.command.rtp:
    description: Lets you randomly teleport
    default: op
  huskrtp.bypass_cooldown:
    description: Lets you bypass all rtp cooldown times
    default: false